# webpack 配置
webpack:
    entry: ./src/main.tsx
    output:
        path: dist
        filename: js/[name].js
        chunkFilename: js/[name].js

# 标题
title: MyApp

# htmlWebpackPlugins配置
html:
    filename: "index.html"
