# webpack 配置
webpack:
    mode: development
    devtool: inline-source-map
    output:
        publicPath: /
        filename: js/[name].js
    devServer:
        port: 8080
        # proxy:
        #     /wechat: http://192.168.1.211:8081

# 环境变量
variable:
    NODE_ENV: development
    publicPath: ${webpack.output.publicPath}
